source "https://rubygems.org"

# This Gemfile enables you to run your Jekyll site locally in an environment
# matching GitHub Pages. To deploy your site to GitHub Pages, push your changes
# to your GitHub repository.

# GitHub Pages currently uses a specific set of gems. To use GitHub Pages,
# uncomment the following line and update to the latest version as needed.
gem "github-pages", "~> 232", group: :jekyll_plugins

# Define plugins in this group to ensure they are available in both local
# development and GitHub Pages environments.
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows, JRuby, and platforms without zoneinfo files need these gems for time zone data.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Improve directory watching performance on Windows.
gem "wdm", "~> 0.1.1", platforms: [:mingw, :x64_mingw, :mswin]

# Ensure compatibility with JRuby by locking `http_parser.rb` to a version with a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]

